### ISSUE TITLE
Dark mode in showcase should change icon color / tint color

### ISSUE THREAD

**Issue by PixelPartner** [lemol/ant-design-icons-elm-ui#1]
In the showcase example, the icons are almost unrecognisable when switched to dark mode with the top right half moon icon.

I used Safari on macOS 10.15 in "daymode".

**Comment by lemol** [comment]
Hi @PixelPartner,

Thank you for your feedback.

At the time I was not aware of the [elm-ui-explorer](https://package.elm-lang.org/packages/kalutheo/elm-ui-explorer/latest) dark mode.

I will prepare the fix.
